# Generated by Django 3.2.5 on 2021-07-08 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comment_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='auctions.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='list',
            name='bids',
        ),
        migrations.AddField(
            model_name='list',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bidders', to='auctions.Bids'),
        ),
        migrations.RemoveField(
            model_name='list',
            name='comments',
        ),
        migrations.AddField(
            model_name='list',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Comment'),
        ),
    ]
