# Generated by Django 3.2.5 on 2021-07-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210708_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
