# Generated by Django 3.2.5 on 2021-07-09 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='comment_user',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='watch_user',
        ),
    ]
