# Generated by Django 3.2.5 on 2021-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210709_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
